library/ihi_simulator/ihi_simulator_battery_lishen/Controllers/BatteryRegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static IHI_SIMULATOR_BATTERY_LISHEN.Ihi_battery_modbus_class;
using Newtonsoft.Json.Linq;
using IHI_SIMULATOR_BATTERY_LISHEN.Models;

namespace IHI_SIMULATOR_BATTERY_LISHEN.Controllers
{
    public class BatteryRegisterController : Controller
    {
        // GET: BatteryRegister
        public ActionResult Index()
        {
            System.Diagnostics.Trace.WriteLine("Enter Battery Register Controller Index");
            return View();
        }

        // GET: BatteryRegister/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: BatteryRegister/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BatteryRegister/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                System.Diagnostics.Trace.WriteLine("Enter Battery Register Controller Create");
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: BatteryRegister/Edit/5
        public ActionResult Edit(int id)
        {
            for (int i = 0; i < Current_RegisterHoldingList.Count; i++)
            {
                JObject oTemp = new JObject();
                oTemp = Current_RegisterHoldingList[i];

                BatteryRegister obj    = new BatteryRegister();
                obj.label               = (string)oTemp["label"];
                obj.index               = (int)oTemp["address"];
                obj.value               = (string)oTemp["value"];
                obj.type                = (string)oTemp["type"];
                obj.slaveid             = "1";

                // Pass register to be edited
                if (id.ToString()==obj.index.ToString())
                {
                    return View(obj);
                }
            }
            return View();
        }

        // POST: BatteryRegister/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // Obtain the register from collection
                string label = Convert.ToString(collection["label"]);
                string value = Convert.ToString(collection["value"]);
                string type  = Convert.ToString(collection["type"]);
                string index = Convert.ToString(collection["index"]);

                System.Diagnostics.Trace.WriteLine("Edited Value Label:"+label +" Value is"+value);
                IHI_SET_REGISTER_VALUE(type, label, index, value);

                return RedirectToAction("ShowRegisters");
            }
            catch
            {
                return View();
            }
        }

        // GET: InverterRegister/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }
        public ActionResult ShowRegisters(FormCollection collection)
        {
            int iRegCounter = 0;
            string strSearchPattern = Convert.ToString(collection["RegisterId"]);
           
            BatteryRegister[] auRegisters = new BatteryRegister[Current_RegisterHoldingList.Count];
            
            System.Diagnostics.Trace.WriteLine("Enter Show Registers:"+collection);

            for (int i = 0; i < Current_RegisterHoldingList.Count; i++)
            {
                JObject oTemp = new JObject();
                oTemp = Current_RegisterHoldingList[i];

                // Create an Inverter Register Object
                BatteryRegister obj = new BatteryRegister();
                obj.label       = (string)oTemp["label"];
                obj.index       = (int)oTemp["address"];
                obj.value       = (string)oTemp["value"];
                obj.type        = (string)oTemp["type"];
                obj.slaveid     = "1";
               
                // Compare patterns of strings
                if (strSearchPattern != null)
                {
                    if (strSearchPattern.Length > 0)
                    {
                        // If no match on label and address then continue
                        if (!obj.label.Contains(strSearchPattern)
                                 &&
                            (!obj.index.ToString().Contains(strSearchPattern)))

                        {
                            continue;
                        }
                    }
                }
               
                // Increment register counter
                auRegisters[iRegCounter] = obj;
                iRegCounter++;
            }
            // Resize the array
            Array.Resize(ref auRegisters,iRegCounter);
            return View(auRegisters);
        }

        // POST: BatteryRegister/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        // POST: BatteryRegister/Delete/5
        [HttpPost]
        public ActionResult Save(int id, FormCollection collection)
        {
            try
            {
                return RedirectToAction("ShowRegisters");
            }
            catch
            {
                return View();
            }
        }
    }
}

library/ihi_simulator/ihi_simulator_battery_lishen/Views/BatteryRegister/Edit.cshtml
@model IHI_SIMULATOR_BATTERY_LISHEN.Models.BatteryRegister

@{
    ViewBag.Title = "Register Edit";
}

<h2>Register Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Register Properties</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.index, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.index, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.index, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.type, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.slaveid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.slaveid, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.slaveid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.label, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.label, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.label, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button runat="server">
                    <span aria-hidden="true" data-toggle="tooltip" title="Update" class="glyphicon glyphicon-send btn-lg bg-primary"></span>
                </button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ShowRegisters")
</div>

library/ihi_simulator/ihi_simulator_battery_lishen/Views/BatteryRegister/ShowRegisters.cshtml
@model IEnumerable<IHI_SIMULATOR_BATTERY_LISHEN.Models.BatteryRegister>


@{
    ViewBag.Title = "IHI Battery Register List";
}

<h2>Battery Register List</h2>
<br />

@using (Html.BeginForm())
{
<div class="form-group">
    <div class="col-md-1" id="search">
        <asp:LinkButton ID="LinkButton1" runat="server" CssClass="btn btn-primary form-control" data-toggle="tooltip" title="Enter Register Label/Modbus Address" OnClick="LinkButton1_Click">
            <i class="glyphicon glyphicon-search"></i> SEARCH
        </asp:LinkButton>
    </div>
    <div class="col-md-3" id="search">
            @Html.Editor("RegisterId", new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessage("Search", "", new { @class = "text-danger" })
     </div>

    <div class="col-md-3" id="search">
      
        <button runat="server">
            <span aria-hidden="true" data-toggle="tooltip" title="Refresh Register List" class="glyphicon glyphicon-refresh btn-lg bg-primary"></span>
        </button>
    </div>
    </div>

    <br />
    <br />
    <br />
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.index)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.slaveid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.label)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.value)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.index)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.slaveid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.label)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.value)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "BatteryRegister", new { id = item.index }, new { @class = "btn btn-info glyphicon glyphicon-edit font-weight:bolder " })
                </td>
            </tr>
        }

    </table>

    }