library/ihi_simulator/ihi_simulator_inverter__pe/Controllers/WarningController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IHI_SIMULATOR_INVERTER_POWER_ELECTRONICS.Models;
using Newtonsoft.Json.Linq;
using static IHI_SIMULATOR_INVERTER_POWER_ELECTRONICS.Ihi_inverter_modbus_class;

namespace ihi_simulator_inverter__pe.Controllers
{
    public class WarningController : Controller
    {
        // GET: Warning
        public ActionResult Index()
        {
            return View();
        }
        // GET: Alarm/Edit/5
        public ActionResult Edit(int id)
        {
            int iRegCounter = 0;
            IHI_SET_REGISTER_VALUE("holding", "warning", "", id.ToString());

            id = id - 1;
            Alarm[] auAlarms = new Alarm[Current_AlarmWarningList.Count];

            // Cycle through all the alarms in the list
            for (int i = 0; i < Current_AlarmWarningList.Count; i++)
            {
                JObject oTemp = new JObject();
                oTemp = Current_AlarmWarningList[i];

                // Create an Inverter Register Object
                Alarm obj = new Alarm();
                obj.id = (string)oTemp["id"];
                obj.description = (string)oTemp["description"];
                obj.state = (string)oTemp["state"];
                if (obj.state == "OFF")
                {
                    if (id == i)
                    {
                        obj.state = "ON";
                        Current_AlarmWarningList[i]["state"] = "ON";
                    }
                }

                // Increment alarm counter
                auAlarms[iRegCounter] = obj;
                iRegCounter++;
            }

            // Resize the alarm array
            Array.Resize(ref auAlarms, iRegCounter);
            return View(auAlarms);
        }
        // GET: Alarm/Clear
        public ActionResult Clear(int id)
        {
            System.Diagnostics.Trace.WriteLine("Enter  Warning:Clear");
            int iRegCounter = 0;
            try
            {
                // Clear the fault
                IHI_SET_REGISTER_VALUE("holding", "warning", "", "0");

                // Reduce to correct index
                id = id - 1;
                Alarm[] auAlarms = new Alarm[Current_AlarmWarningList.Count];

                // Cycle through all the alarms in the list
                for (int i = 0; i < Current_AlarmWarningList.Count; i++)
                {
                    JObject oTemp = new JObject();
                    oTemp = Current_AlarmWarningList[i];

                    // Set initial state of alarm to OFF
                    Current_AlarmWarningList[i]["state"] = "OFF";

                    // Create an Inverter Register Object
                    Alarm obj = new Alarm();
                    obj.id = (string)oTemp["id"];
                    obj.description = (string)oTemp["description"];
                    obj.state = (string)oTemp["state"];

                    // Increment alarm counter
                    auAlarms[iRegCounter] = obj;
                    iRegCounter++;
                }

                // Resize the alarm array
                Array.Resize(ref auAlarms, iRegCounter);
                return View(auAlarms);
            }
            catch
            {
                return View();
            }

        }
        public ActionResult ShowAlarms(FormCollection collection)
        {
            int iRegCounter = 0;

            Alarm[] auAlarms = new Alarm[Current_AlarmWarningList.Count];

            // Cycle through all the alarms in the list
            for (int i = 0; i < Current_AlarmWarningList.Count; i++)
            {
                JObject oTemp = new JObject();
                oTemp = Current_AlarmWarningList[i];

                // Create an Inverter Register Object
                Alarm obj = new Alarm();
                obj.id = (string)oTemp["id"];
                obj.description = (string)oTemp["description"];
                obj.state = (string)oTemp["state"];

                // Increment warning counter
                auAlarms[iRegCounter] = obj;
                iRegCounter++;
            }  // Resize the warning array
            Array.Resize(ref auAlarms, iRegCounter);
            return View(auAlarms);
        }


        // GET: Warning/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Warning/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Warning/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // POST: Warning/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Warning/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Warning/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

library/ihi_simulator/ihi_simulator_inverter__pe/Views/Warning/Clear.cshtml
@model IEnumerable<IHI_SIMULATOR_INVERTER_POWER_ELECTRONICS.Models.Alarm>

@{
    ViewBag.Title = "Inverter Warnings";
}

<h2>Inverter Alarms</h2>
<div class="form-group">

    <div class="col-md-10">
        @Html.ActionLink(" ", "Warning", new { id = "0" }, new { @class = "btn btn-success glyphicon glyphicon-bell font-weight:bolder", @toggle="tooltip", @title="clear all alarms" })
    </div>
</div>
<br />
<br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.state)
        </th>
        <th></th>
    </tr>


    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.state)
            </td>
            <td>
                @Html.ActionLink(" ", "Edit", "Warning", new { id = item.id }, new { @class = "btn btn-danger glyphicon glyphicon-bell font-weight:bolder", @toggle = "tooltip", @title = "trigger alarm" })
            </td>
        </tr>
    }
</table>

library/ihi_simulator/ihi_simulator_inverter__pe/Views/Warning/Edit.cshtml
@model IEnumerable<IHI_SIMULATOR_INVERTER_POWER_ELECTRONICS.Models.Alarm>

@{
    ViewBag.Title = "Inverter Warnings";
}

<h2>Inverter Alarms</h2>
<div class="form-group">
   
    <div class="col-md-10">
        @Html.ActionLink(" ", "Clear", "Warning", new { id = "0" }, new { @class = "btn btn-success glyphicon glyphicon-bell font-weight:bolder", @toggle = "tooltip", @title = "clear all alarms" })
    </div>
</div>
<br />
<br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.state)
        </th>
        <th></th>
    </tr>


    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.state)
            </td>
            <td>
             
                @Html.ActionLink(" ", "Edit", "Warning", new { id = item.id }, new { @class = "btn btn-danger glyphicon glyphicon-bell font-weight:bolder", @toggle = "tooltip", @title = "trigger alarm" })
            </td>
        </tr>
    }
</table>

library/ihi_simulator/ihi_simulator_inverter__pe/Views/Warning/ShowAlarms.cshtml
@model IEnumerable<IHI_SIMULATOR_INVERTER_POWER_ELECTRONICS.Models.Alarm>

@{
    ViewBag.Title = "Inverter Warnings";
}

<h2>Inverter Alarms</h2>

<div class="form-group">

    <div class="col-md-10">
        @Html.ActionLink(" ", "Clear", "Warning", new { id = "0" }, new { @class = "btn btn-success glyphicon glyphicon-bell font-weight:bolder", @toggle = "tooltip", @title = "clear all alarms" })
    </div>
</div>
<br />
<br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.state)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.state)
        </td>
        <td>
            @Html.ActionLink(" ", "Edit", "Warning", new { id = item.id }, new { @class = "btn btn-danger glyphicon glyphicon-bell font-weight:bolder", @toggle = "tooltip", @title = "trigger alarm" })
        </td>
    </tr>
}
</table>